#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_65818_brdhc")]
public partial class careersDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertbrdhc_JobPost(brdhc_JobPost instance);
  partial void Updatebrdhc_JobPost(brdhc_JobPost instance);
  partial void Deletebrdhc_JobPost(brdhc_JobPost instance);
  #endregion
	
	public careersDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["myCon"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public careersDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public careersDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public careersDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public careersDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<brdhc_JobPost> brdhc_JobPosts
	{
		get
		{
			return this.GetTable<brdhc_JobPost>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.brdhc_JobPosts")]
public partial class brdhc_JobPost : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _JobPostId;
	
	private System.Guid _JobCategoryId;
	
	private string _JobPostTitle;
	
	private string _JobPostDescription;
	
	private System.DateTime _JobPostingDate;
	
	private System.DateTime _ExpDate;
	
	private string _ContactEmail;
	
	private System.Nullable<bool> _IsActive;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJobPostIdChanging(System.Guid value);
    partial void OnJobPostIdChanged();
    partial void OnJobCategoryIdChanging(System.Guid value);
    partial void OnJobCategoryIdChanged();
    partial void OnJobPostTitleChanging(string value);
    partial void OnJobPostTitleChanged();
    partial void OnJobPostDescriptionChanging(string value);
    partial void OnJobPostDescriptionChanged();
    partial void OnJobPostingDateChanging(System.DateTime value);
    partial void OnJobPostingDateChanged();
    partial void OnExpDateChanging(System.DateTime value);
    partial void OnExpDateChanged();
    partial void OnContactEmailChanging(string value);
    partial void OnContactEmailChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    #endregion
	
	public brdhc_JobPost()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobPostId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid JobPostId
	{
		get
		{
			return this._JobPostId;
		}
		set
		{
			if ((this._JobPostId != value))
			{
				this.OnJobPostIdChanging(value);
				this.SendPropertyChanging();
				this._JobPostId = value;
				this.SendPropertyChanged("JobPostId");
				this.OnJobPostIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobCategoryId", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid JobCategoryId
	{
		get
		{
			return this._JobCategoryId;
		}
		set
		{
			if ((this._JobCategoryId != value))
			{
				this.OnJobCategoryIdChanging(value);
				this.SendPropertyChanging();
				this._JobCategoryId = value;
				this.SendPropertyChanged("JobCategoryId");
				this.OnJobCategoryIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobPostTitle", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string JobPostTitle
	{
		get
		{
			return this._JobPostTitle;
		}
		set
		{
			if ((this._JobPostTitle != value))
			{
				this.OnJobPostTitleChanging(value);
				this.SendPropertyChanging();
				this._JobPostTitle = value;
				this.SendPropertyChanged("JobPostTitle");
				this.OnJobPostTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobPostDescription", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string JobPostDescription
	{
		get
		{
			return this._JobPostDescription;
		}
		set
		{
			if ((this._JobPostDescription != value))
			{
				this.OnJobPostDescriptionChanging(value);
				this.SendPropertyChanging();
				this._JobPostDescription = value;
				this.SendPropertyChanged("JobPostDescription");
				this.OnJobPostDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobPostingDate", DbType="Date NOT NULL")]
	public System.DateTime JobPostingDate
	{
		get
		{
			return this._JobPostingDate;
		}
		set
		{
			if ((this._JobPostingDate != value))
			{
				this.OnJobPostingDateChanging(value);
				this.SendPropertyChanging();
				this._JobPostingDate = value;
				this.SendPropertyChanged("JobPostingDate");
				this.OnJobPostingDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpDate", DbType="Date NOT NULL")]
	public System.DateTime ExpDate
	{
		get
		{
			return this._ExpDate;
		}
		set
		{
			if ((this._ExpDate != value))
			{
				this.OnExpDateChanging(value);
				this.SendPropertyChanging();
				this._ExpDate = value;
				this.SendPropertyChanged("ExpDate");
				this.OnExpDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactEmail", DbType="VarChar(50)")]
	public string ContactEmail
	{
		get
		{
			return this._ContactEmail;
		}
		set
		{
			if ((this._ContactEmail != value))
			{
				this.OnContactEmailChanging(value);
				this.SendPropertyChanging();
				this._ContactEmail = value;
				this.SendPropertyChanged("ContactEmail");
				this.OnContactEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
	public System.Nullable<bool> IsActive
	{
		get
		{
			return this._IsActive;
		}
		set
		{
			if ((this._IsActive != value))
			{
				this.OnIsActiveChanging(value);
				this.SendPropertyChanging();
				this._IsActive = value;
				this.SendPropertyChanged("IsActive");
				this.OnIsActiveChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
