#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_65818_brdhc")]
public partial class CommonDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertbrdhc_City(brdhc_City instance);
  partial void Updatebrdhc_City(brdhc_City instance);
  partial void Deletebrdhc_City(brdhc_City instance);
  partial void Insertbrdhc_Country(brdhc_Country instance);
  partial void Updatebrdhc_Country(brdhc_Country instance);
  partial void Deletebrdhc_Country(brdhc_Country instance);
  partial void Insertbrdhc_State(brdhc_State instance);
  partial void Updatebrdhc_State(brdhc_State instance);
  partial void Deletebrdhc_State(brdhc_State instance);
  partial void Insertbrdhc_DashboardMenus(brdhc_DashboardMenus instance);
  partial void Updatebrdhc_DashboardMenus(brdhc_DashboardMenus instance);
  partial void Deletebrdhc_DashboardMenus(brdhc_DashboardMenus instance);
  partial void Insertbrdhc_ErrorLog(brdhc_ErrorLog instance);
  partial void Updatebrdhc_ErrorLog(brdhc_ErrorLog instance);
  partial void Deletebrdhc_ErrorLog(brdhc_ErrorLog instance);
  #endregion
	
	public CommonDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["myCon"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public CommonDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public CommonDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public CommonDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public CommonDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<brdhc_City> brdhc_Cities
	{
		get
		{
			return this.GetTable<brdhc_City>();
		}
	}
	
	public System.Data.Linq.Table<brdhc_Country> brdhc_Countries
	{
		get
		{
			return this.GetTable<brdhc_Country>();
		}
	}
	
	public System.Data.Linq.Table<brdhc_State> brdhc_States
	{
		get
		{
			return this.GetTable<brdhc_State>();
		}
	}
	
	public System.Data.Linq.Table<brdhc_DashboardMenus> brdhc_DashboardMenus
	{
		get
		{
			return this.GetTable<brdhc_DashboardMenus>();
		}
	}
	
	public System.Data.Linq.Table<brdhc_ErrorLog> brdhc_ErrorLogs
	{
		get
		{
			return this.GetTable<brdhc_ErrorLog>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getAlertSubscribers")]
	public ISingleResult<sp_getAlertSubscribersResult> sp_getAlertSubscribers([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplicationName", DbType="NVarChar(256)")] string applicationName)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), applicationName);
		return ((ISingleResult<sp_getAlertSubscribersResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.brdhc_Cities")]
public partial class brdhc_City : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _CityId;
	
	private System.Guid _StateId;
	
	private string _City;
	
	private EntityRef<brdhc_State> _brdhc_State;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCityIdChanging(System.Guid value);
    partial void OnCityIdChanged();
    partial void OnStateIdChanging(System.Guid value);
    partial void OnStateIdChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    #endregion
	
	public brdhc_City()
	{
		this._brdhc_State = default(EntityRef<brdhc_State>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid CityId
	{
		get
		{
			return this._CityId;
		}
		set
		{
			if ((this._CityId != value))
			{
				this.OnCityIdChanging(value);
				this.SendPropertyChanging();
				this._CityId = value;
				this.SendPropertyChanged("CityId");
				this.OnCityIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateId", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid StateId
	{
		get
		{
			return this._StateId;
		}
		set
		{
			if ((this._StateId != value))
			{
				if (this._brdhc_State.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnStateIdChanging(value);
				this.SendPropertyChanging();
				this._StateId = value;
				this.SendPropertyChanged("StateId");
				this.OnStateIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="brdhc_State_brdhc_City", Storage="_brdhc_State", ThisKey="StateId", OtherKey="StateId", IsForeignKey=true)]
	public brdhc_State brdhc_State
	{
		get
		{
			return this._brdhc_State.Entity;
		}
		set
		{
			brdhc_State previousValue = this._brdhc_State.Entity;
			if (((previousValue != value) 
						|| (this._brdhc_State.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._brdhc_State.Entity = null;
					previousValue.brdhc_Cities.Remove(this);
				}
				this._brdhc_State.Entity = value;
				if ((value != null))
				{
					value.brdhc_Cities.Add(this);
					this._StateId = value.StateId;
				}
				else
				{
					this._StateId = default(System.Guid);
				}
				this.SendPropertyChanged("brdhc_State");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.brdhc_Country")]
public partial class brdhc_Country : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _CountryId;
	
	private string _Country;
	
	private EntitySet<brdhc_State> _brdhc_States;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCountryIdChanging(System.Guid value);
    partial void OnCountryIdChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    #endregion
	
	public brdhc_Country()
	{
		this._brdhc_States = new EntitySet<brdhc_State>(new Action<brdhc_State>(this.attach_brdhc_States), new Action<brdhc_State>(this.detach_brdhc_States));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid CountryId
	{
		get
		{
			return this._CountryId;
		}
		set
		{
			if ((this._CountryId != value))
			{
				this.OnCountryIdChanging(value);
				this.SendPropertyChanging();
				this._CountryId = value;
				this.SendPropertyChanged("CountryId");
				this.OnCountryIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Country
	{
		get
		{
			return this._Country;
		}
		set
		{
			if ((this._Country != value))
			{
				this.OnCountryChanging(value);
				this.SendPropertyChanging();
				this._Country = value;
				this.SendPropertyChanged("Country");
				this.OnCountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="brdhc_Country_brdhc_State", Storage="_brdhc_States", ThisKey="CountryId", OtherKey="CountryId")]
	public EntitySet<brdhc_State> brdhc_States
	{
		get
		{
			return this._brdhc_States;
		}
		set
		{
			this._brdhc_States.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_brdhc_States(brdhc_State entity)
	{
		this.SendPropertyChanging();
		entity.brdhc_Country = this;
	}
	
	private void detach_brdhc_States(brdhc_State entity)
	{
		this.SendPropertyChanging();
		entity.brdhc_Country = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.brdhc_States")]
public partial class brdhc_State : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _StateId;
	
	private System.Guid _CountryId;
	
	private string _State;
	
	private EntitySet<brdhc_City> _brdhc_Cities;
	
	private EntityRef<brdhc_Country> _brdhc_Country;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStateIdChanging(System.Guid value);
    partial void OnStateIdChanged();
    partial void OnCountryIdChanging(System.Guid value);
    partial void OnCountryIdChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    #endregion
	
	public brdhc_State()
	{
		this._brdhc_Cities = new EntitySet<brdhc_City>(new Action<brdhc_City>(this.attach_brdhc_Cities), new Action<brdhc_City>(this.detach_brdhc_Cities));
		this._brdhc_Country = default(EntityRef<brdhc_Country>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StateId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid StateId
	{
		get
		{
			return this._StateId;
		}
		set
		{
			if ((this._StateId != value))
			{
				this.OnStateIdChanging(value);
				this.SendPropertyChanging();
				this._StateId = value;
				this.SendPropertyChanged("StateId");
				this.OnStateIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryId", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid CountryId
	{
		get
		{
			return this._CountryId;
		}
		set
		{
			if ((this._CountryId != value))
			{
				if (this._brdhc_Country.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnCountryIdChanging(value);
				this.SendPropertyChanging();
				this._CountryId = value;
				this.SendPropertyChanged("CountryId");
				this.OnCountryIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="brdhc_State_brdhc_City", Storage="_brdhc_Cities", ThisKey="StateId", OtherKey="StateId")]
	public EntitySet<brdhc_City> brdhc_Cities
	{
		get
		{
			return this._brdhc_Cities;
		}
		set
		{
			this._brdhc_Cities.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="brdhc_Country_brdhc_State", Storage="_brdhc_Country", ThisKey="CountryId", OtherKey="CountryId", IsForeignKey=true)]
	public brdhc_Country brdhc_Country
	{
		get
		{
			return this._brdhc_Country.Entity;
		}
		set
		{
			brdhc_Country previousValue = this._brdhc_Country.Entity;
			if (((previousValue != value) 
						|| (this._brdhc_Country.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._brdhc_Country.Entity = null;
					previousValue.brdhc_States.Remove(this);
				}
				this._brdhc_Country.Entity = value;
				if ((value != null))
				{
					value.brdhc_States.Add(this);
					this._CountryId = value.CountryId;
				}
				else
				{
					this._CountryId = default(System.Guid);
				}
				this.SendPropertyChanged("brdhc_Country");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_brdhc_Cities(brdhc_City entity)
	{
		this.SendPropertyChanging();
		entity.brdhc_State = this;
	}
	
	private void detach_brdhc_Cities(brdhc_City entity)
	{
		this.SendPropertyChanging();
		entity.brdhc_State = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.brdhc_DashboardMenus")]
public partial class brdhc_DashboardMenus : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _MenuId;
	
	private string _MenuTitle;
	
	private string _MenuUrl;
	
	private string _RoleName;
	
	private System.Nullable<bool> _Status;
	
	private System.Nullable<int> _ParentId;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMenuIdChanging(int value);
    partial void OnMenuIdChanged();
    partial void OnMenuTitleChanging(string value);
    partial void OnMenuTitleChanged();
    partial void OnMenuUrlChanging(string value);
    partial void OnMenuUrlChanged();
    partial void OnRoleNameChanging(string value);
    partial void OnRoleNameChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    partial void OnParentIdChanging(System.Nullable<int> value);
    partial void OnParentIdChanged();
    #endregion
	
	public brdhc_DashboardMenus()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int MenuId
	{
		get
		{
			return this._MenuId;
		}
		set
		{
			if ((this._MenuId != value))
			{
				this.OnMenuIdChanging(value);
				this.SendPropertyChanging();
				this._MenuId = value;
				this.SendPropertyChanged("MenuId");
				this.OnMenuIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuTitle", DbType="VarChar(50)")]
	public string MenuTitle
	{
		get
		{
			return this._MenuTitle;
		}
		set
		{
			if ((this._MenuTitle != value))
			{
				this.OnMenuTitleChanging(value);
				this.SendPropertyChanging();
				this._MenuTitle = value;
				this.SendPropertyChanged("MenuTitle");
				this.OnMenuTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MenuUrl", DbType="VarChar(100)")]
	public string MenuUrl
	{
		get
		{
			return this._MenuUrl;
		}
		set
		{
			if ((this._MenuUrl != value))
			{
				this.OnMenuUrlChanging(value);
				this.SendPropertyChanging();
				this._MenuUrl = value;
				this.SendPropertyChanged("MenuUrl");
				this.OnMenuUrlChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="VarChar(50)")]
	public string RoleName
	{
		get
		{
			return this._RoleName;
		}
		set
		{
			if ((this._RoleName != value))
			{
				this.OnRoleNameChanging(value);
				this.SendPropertyChanging();
				this._RoleName = value;
				this.SendPropertyChanged("RoleName");
				this.OnRoleNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
	public System.Nullable<bool> Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentId", DbType="Int")]
	public System.Nullable<int> ParentId
	{
		get
		{
			return this._ParentId;
		}
		set
		{
			if ((this._ParentId != value))
			{
				this.OnParentIdChanging(value);
				this.SendPropertyChanging();
				this._ParentId = value;
				this.SendPropertyChanged("ParentId");
				this.OnParentIdChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.brdhc_ErrorLogs")]
public partial class brdhc_ErrorLog : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ErrorId;
	
	private string _FileName;
	
	private string _MethodName;
	
	private string _EventName;
	
	private System.Nullable<int> _LineNumber;
	
	private System.Nullable<int> _ColumnNumber;
	
	private string _Message;
	
	private string _ExceptionType;
	
	private System.Nullable<System.DateTime> _ExceptionTime;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnErrorIdChanging(int value);
    partial void OnErrorIdChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    partial void OnMethodNameChanging(string value);
    partial void OnMethodNameChanged();
    partial void OnEventNameChanging(string value);
    partial void OnEventNameChanged();
    partial void OnLineNumberChanging(System.Nullable<int> value);
    partial void OnLineNumberChanged();
    partial void OnColumnNumberChanging(System.Nullable<int> value);
    partial void OnColumnNumberChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnExceptionTypeChanging(string value);
    partial void OnExceptionTypeChanged();
    partial void OnExceptionTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnExceptionTimeChanged();
    #endregion
	
	public brdhc_ErrorLog()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ErrorId
	{
		get
		{
			return this._ErrorId;
		}
		set
		{
			if ((this._ErrorId != value))
			{
				this.OnErrorIdChanging(value);
				this.SendPropertyChanging();
				this._ErrorId = value;
				this.SendPropertyChanged("ErrorId");
				this.OnErrorIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(200)")]
	public string FileName
	{
		get
		{
			return this._FileName;
		}
		set
		{
			if ((this._FileName != value))
			{
				this.OnFileNameChanging(value);
				this.SendPropertyChanging();
				this._FileName = value;
				this.SendPropertyChanged("FileName");
				this.OnFileNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MethodName", DbType="VarChar(200)")]
	public string MethodName
	{
		get
		{
			return this._MethodName;
		}
		set
		{
			if ((this._MethodName != value))
			{
				this.OnMethodNameChanging(value);
				this.SendPropertyChanging();
				this._MethodName = value;
				this.SendPropertyChanged("MethodName");
				this.OnMethodNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EventName", DbType="VarChar(200)")]
	public string EventName
	{
		get
		{
			return this._EventName;
		}
		set
		{
			if ((this._EventName != value))
			{
				this.OnEventNameChanging(value);
				this.SendPropertyChanging();
				this._EventName = value;
				this.SendPropertyChanged("EventName");
				this.OnEventNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineNumber", DbType="Int")]
	public System.Nullable<int> LineNumber
	{
		get
		{
			return this._LineNumber;
		}
		set
		{
			if ((this._LineNumber != value))
			{
				this.OnLineNumberChanging(value);
				this.SendPropertyChanging();
				this._LineNumber = value;
				this.SendPropertyChanged("LineNumber");
				this.OnLineNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColumnNumber", DbType="Int")]
	public System.Nullable<int> ColumnNumber
	{
		get
		{
			return this._ColumnNumber;
		}
		set
		{
			if ((this._ColumnNumber != value))
			{
				this.OnColumnNumberChanging(value);
				this.SendPropertyChanging();
				this._ColumnNumber = value;
				this.SendPropertyChanged("ColumnNumber");
				this.OnColumnNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="VarChar(500)")]
	public string Message
	{
		get
		{
			return this._Message;
		}
		set
		{
			if ((this._Message != value))
			{
				this.OnMessageChanging(value);
				this.SendPropertyChanging();
				this._Message = value;
				this.SendPropertyChanged("Message");
				this.OnMessageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExceptionType", DbType="VarChar(100)")]
	public string ExceptionType
	{
		get
		{
			return this._ExceptionType;
		}
		set
		{
			if ((this._ExceptionType != value))
			{
				this.OnExceptionTypeChanging(value);
				this.SendPropertyChanging();
				this._ExceptionType = value;
				this.SendPropertyChanged("ExceptionType");
				this.OnExceptionTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExceptionTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> ExceptionTime
	{
		get
		{
			return this._ExceptionTime;
		}
		set
		{
			if ((this._ExceptionTime != value))
			{
				this.OnExceptionTimeChanging(value);
				this.SendPropertyChanging();
				this._ExceptionTime = value;
				this.SendPropertyChanged("ExceptionTime");
				this.OnExceptionTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class sp_getAlertSubscribersResult
{
	
	private string _Email;
	
	private string _Name;
	
	private System.Guid _UserId;
	
	public sp_getAlertSubscribersResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(256)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this._Email = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(101) NOT NULL", CanBeNull=false)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this._Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				this._UserId = value;
			}
		}
	}
}
#pragma warning restore 1591
