#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_65818_brdhc")]
public partial class HealthAlertsDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertbrdhc_HealthAlert(brdhc_HealthAlert instance);
  partial void Updatebrdhc_HealthAlert(brdhc_HealthAlert instance);
  partial void Deletebrdhc_HealthAlert(brdhc_HealthAlert instance);
  #endregion
	
	public HealthAlertsDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["myCon"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public HealthAlertsDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public HealthAlertsDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public HealthAlertsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public HealthAlertsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<brdhc_HealthAlert> brdhc_HealthAlerts
	{
		get
		{
			return this.GetTable<brdhc_HealthAlert>();
		}
	}
	
	public System.Data.Linq.Table<brdhc_AlertSubscriber> brdhc_AlertSubscribers
	{
		get
		{
			return this.GetTable<brdhc_AlertSubscriber>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_SearchHealthAlertsByName")]
	public ISingleResult<sp_SearchHealthAlertsByNameResult> sp_SearchHealthAlertsByName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplicationName", DbType="NVarChar(256)")] string applicationName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HealthAlertTitle", DbType="NVarChar(256)")] string healthAlertTitle)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), applicationName, healthAlertTitle);
		return ((ISingleResult<sp_SearchHealthAlertsByNameResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.brdhc_HealthAlerts")]
public partial class brdhc_HealthAlert : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _HealthAlertId;
	
	private string _HealthAlertTitle;
	
	private string _HealthAlertDescription;
	
	private System.DateTime _AlertDate;
	
	private System.Guid _UserId;
	
	private bool _Published;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHealthAlertIdChanging(System.Guid value);
    partial void OnHealthAlertIdChanged();
    partial void OnHealthAlertTitleChanging(string value);
    partial void OnHealthAlertTitleChanged();
    partial void OnHealthAlertDescriptionChanging(string value);
    partial void OnHealthAlertDescriptionChanged();
    partial void OnAlertDateChanging(System.DateTime value);
    partial void OnAlertDateChanged();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnPublishedChanging(bool value);
    partial void OnPublishedChanged();
    #endregion
	
	public brdhc_HealthAlert()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HealthAlertId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid HealthAlertId
	{
		get
		{
			return this._HealthAlertId;
		}
		set
		{
			if ((this._HealthAlertId != value))
			{
				this.OnHealthAlertIdChanging(value);
				this.SendPropertyChanging();
				this._HealthAlertId = value;
				this.SendPropertyChanged("HealthAlertId");
				this.OnHealthAlertIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HealthAlertTitle", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string HealthAlertTitle
	{
		get
		{
			return this._HealthAlertTitle;
		}
		set
		{
			if ((this._HealthAlertTitle != value))
			{
				this.OnHealthAlertTitleChanging(value);
				this.SendPropertyChanging();
				this._HealthAlertTitle = value;
				this.SendPropertyChanged("HealthAlertTitle");
				this.OnHealthAlertTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HealthAlertDescription", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string HealthAlertDescription
	{
		get
		{
			return this._HealthAlertDescription;
		}
		set
		{
			if ((this._HealthAlertDescription != value))
			{
				this.OnHealthAlertDescriptionChanging(value);
				this.SendPropertyChanging();
				this._HealthAlertDescription = value;
				this.SendPropertyChanged("HealthAlertDescription");
				this.OnHealthAlertDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlertDate", DbType="Date NOT NULL")]
	public System.DateTime AlertDate
	{
		get
		{
			return this._AlertDate;
		}
		set
		{
			if ((this._AlertDate != value))
			{
				this.OnAlertDateChanging(value);
				this.SendPropertyChanging();
				this._AlertDate = value;
				this.SendPropertyChanged("AlertDate");
				this.OnAlertDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				this.OnUserIdChanging(value);
				this.SendPropertyChanging();
				this._UserId = value;
				this.SendPropertyChanged("UserId");
				this.OnUserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Published", DbType="Bit NOT NULL")]
	public bool Published
	{
		get
		{
			return this._Published;
		}
		set
		{
			if ((this._Published != value))
			{
				this.OnPublishedChanging(value);
				this.SendPropertyChanging();
				this._Published = value;
				this.SendPropertyChanged("Published");
				this.OnPublishedChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.brdhc_AlertSubscribers")]
public partial class brdhc_AlertSubscriber
{
	
	private System.Guid _UserId;
	
	public brdhc_AlertSubscriber()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				this._UserId = value;
			}
		}
	}
}

public partial class sp_SearchHealthAlertsByNameResult
{
	
	private System.Guid _HealthAlertId;
	
	private string _HealthAlertTitle;
	
	private string _HealthAlertDescription;
	
	private string _AlertDate;
	
	private string _Published;
	
	public sp_SearchHealthAlertsByNameResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HealthAlertId", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid HealthAlertId
	{
		get
		{
			return this._HealthAlertId;
		}
		set
		{
			if ((this._HealthAlertId != value))
			{
				this._HealthAlertId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HealthAlertTitle", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string HealthAlertTitle
	{
		get
		{
			return this._HealthAlertTitle;
		}
		set
		{
			if ((this._HealthAlertTitle != value))
			{
				this._HealthAlertTitle = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HealthAlertDescription", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string HealthAlertDescription
	{
		get
		{
			return this._HealthAlertDescription;
		}
		set
		{
			if ((this._HealthAlertDescription != value))
			{
				this._HealthAlertDescription = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlertDate", DbType="VarChar(12)")]
	public string AlertDate
	{
		get
		{
			return this._AlertDate;
		}
		set
		{
			if ((this._AlertDate != value))
			{
				this._AlertDate = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Published", DbType="VarChar(13) NOT NULL", CanBeNull=false)]
	public string Published
	{
		get
		{
			return this._Published;
		}
		set
		{
			if ((this._Published != value))
			{
				this._Published = value;
			}
		}
	}
}
#pragma warning restore 1591
