#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_65818_brdhc")]
public partial class InvoicesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertbrdhc_Invoice(brdhc_Invoice instance);
  partial void Updatebrdhc_Invoice(brdhc_Invoice instance);
  partial void Deletebrdhc_Invoice(brdhc_Invoice instance);
  #endregion
	
	public InvoicesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["myCon"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public InvoicesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public InvoicesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public InvoicesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public InvoicesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<brdhc_Invoice> brdhc_Invoices
	{
		get
		{
			return this.GetTable<brdhc_Invoice>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getInvoiceByDocName")]
	public ISingleResult<sp_getInvoiceByDocNameResult> sp_getInvoiceByDocName([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string docUName)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), docUName);
		return ((ISingleResult<sp_getInvoiceByDocNameResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getInvoiceByDocStatus")]
	public ISingleResult<sp_getInvoiceByDocStatusResult> sp_getInvoiceByDocStatus([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string docUName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string status)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), docUName, status);
		return ((ISingleResult<sp_getInvoiceByDocStatusResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.brdhc_Invoice")]
public partial class brdhc_Invoice : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _InvoiceID;
	
	private System.Guid _PatientID;
	
	private System.DateTime _CreatedOn;
	
	private double _TotalAmt;
	
	private string _CreatedBy;
	
	private string _Status;
	
	private string _Reason;
	
	private System.DateTime _DueOn;
	
	private string _TransactionID;
	
	private System.Nullable<System.DateTime> _PaidOn;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInvoiceIDChanging(System.Guid value);
    partial void OnInvoiceIDChanged();
    partial void OnPatientIDChanging(System.Guid value);
    partial void OnPatientIDChanged();
    partial void OnCreatedOnChanging(System.DateTime value);
    partial void OnCreatedOnChanged();
    partial void OnTotalAmtChanging(double value);
    partial void OnTotalAmtChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnReasonChanging(string value);
    partial void OnReasonChanged();
    partial void OnDueOnChanging(System.DateTime value);
    partial void OnDueOnChanged();
    partial void OnTransactionIDChanging(string value);
    partial void OnTransactionIDChanged();
    partial void OnPaidOnChanging(System.Nullable<System.DateTime> value);
    partial void OnPaidOnChanged();
    #endregion
	
	public brdhc_Invoice()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid InvoiceID
	{
		get
		{
			return this._InvoiceID;
		}
		set
		{
			if ((this._InvoiceID != value))
			{
				this.OnInvoiceIDChanging(value);
				this.SendPropertyChanging();
				this._InvoiceID = value;
				this.SendPropertyChanged("InvoiceID");
				this.OnInvoiceIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this.OnPatientIDChanging(value);
				this.SendPropertyChanging();
				this._PatientID = value;
				this.SendPropertyChanged("PatientID");
				this.OnPatientIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="Date NOT NULL")]
	public System.DateTime CreatedOn
	{
		get
		{
			return this._CreatedOn;
		}
		set
		{
			if ((this._CreatedOn != value))
			{
				this.OnCreatedOnChanging(value);
				this.SendPropertyChanging();
				this._CreatedOn = value;
				this.SendPropertyChanged("CreatedOn");
				this.OnCreatedOnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmt", DbType="Float NOT NULL")]
	public double TotalAmt
	{
		get
		{
			return this._TotalAmt;
		}
		set
		{
			if ((this._TotalAmt != value))
			{
				this.OnTotalAmtChanging(value);
				this.SendPropertyChanging();
				this._TotalAmt = value;
				this.SendPropertyChanged("TotalAmt");
				this.OnTotalAmtChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string CreatedBy
	{
		get
		{
			return this._CreatedBy;
		}
		set
		{
			if ((this._CreatedBy != value))
			{
				this.OnCreatedByChanging(value);
				this.SendPropertyChanging();
				this._CreatedBy = value;
				this.SendPropertyChanged("CreatedBy");
				this.OnCreatedByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Reason
	{
		get
		{
			return this._Reason;
		}
		set
		{
			if ((this._Reason != value))
			{
				this.OnReasonChanging(value);
				this.SendPropertyChanging();
				this._Reason = value;
				this.SendPropertyChanged("Reason");
				this.OnReasonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueOn", DbType="Date NOT NULL")]
	public System.DateTime DueOn
	{
		get
		{
			return this._DueOn;
		}
		set
		{
			if ((this._DueOn != value))
			{
				this.OnDueOnChanging(value);
				this.SendPropertyChanging();
				this._DueOn = value;
				this.SendPropertyChanged("DueOn");
				this.OnDueOnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionID", DbType="VarChar(MAX)")]
	public string TransactionID
	{
		get
		{
			return this._TransactionID;
		}
		set
		{
			if ((this._TransactionID != value))
			{
				this.OnTransactionIDChanging(value);
				this.SendPropertyChanging();
				this._TransactionID = value;
				this.SendPropertyChanged("TransactionID");
				this.OnTransactionIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaidOn", DbType="DateTime")]
	public System.Nullable<System.DateTime> PaidOn
	{
		get
		{
			return this._PaidOn;
		}
		set
		{
			if ((this._PaidOn != value))
			{
				this.OnPaidOnChanging(value);
				this.SendPropertyChanging();
				this._PaidOn = value;
				this.SendPropertyChanged("PaidOn");
				this.OnPaidOnChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class sp_getInvoiceByDocNameResult
{
	
	private string _PatientName;
	
	private System.Guid _InvoiceID;
	
	private System.Guid _PatientID;
	
	private System.DateTime _CreatedOn;
	
	private System.Nullable<double> _TotalAmt;
	
	private string _CreatedBy;
	
	private string _Status;
	
	private string _Reason;
	
	private System.DateTime _DueOn;
	
	public sp_getInvoiceByDocNameResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientName", DbType="VarChar(101) NOT NULL", CanBeNull=false)]
	public string PatientName
	{
		get
		{
			return this._PatientName;
		}
		set
		{
			if ((this._PatientName != value))
			{
				this._PatientName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceID", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid InvoiceID
	{
		get
		{
			return this._InvoiceID;
		}
		set
		{
			if ((this._InvoiceID != value))
			{
				this._InvoiceID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this._PatientID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="Date NOT NULL")]
	public System.DateTime CreatedOn
	{
		get
		{
			return this._CreatedOn;
		}
		set
		{
			if ((this._CreatedOn != value))
			{
				this._CreatedOn = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmt", DbType="Float")]
	public System.Nullable<double> TotalAmt
	{
		get
		{
			return this._TotalAmt;
		}
		set
		{
			if ((this._TotalAmt != value))
			{
				this._TotalAmt = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string CreatedBy
	{
		get
		{
			return this._CreatedBy;
		}
		set
		{
			if ((this._CreatedBy != value))
			{
				this._CreatedBy = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this._Status = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Reason
	{
		get
		{
			return this._Reason;
		}
		set
		{
			if ((this._Reason != value))
			{
				this._Reason = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueOn", DbType="Date NOT NULL")]
	public System.DateTime DueOn
	{
		get
		{
			return this._DueOn;
		}
		set
		{
			if ((this._DueOn != value))
			{
				this._DueOn = value;
			}
		}
	}
}

public partial class sp_getInvoiceByDocStatusResult
{
	
	private string _PatientName;
	
	private System.Guid _InvoiceID;
	
	private System.Guid _PatientID;
	
	private System.DateTime _CreatedOn;
	
	private double _TotalAmt;
	
	private string _CreatedBy;
	
	private string _Status;
	
	private string _Reason;
	
	private System.DateTime _DueOn;
	
	private string _TransactionID;
	
	private System.Nullable<System.DateTime> _PaidOn;
	
	public sp_getInvoiceByDocStatusResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientName", DbType="VarChar(101) NOT NULL", CanBeNull=false)]
	public string PatientName
	{
		get
		{
			return this._PatientName;
		}
		set
		{
			if ((this._PatientName != value))
			{
				this._PatientName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceID", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid InvoiceID
	{
		get
		{
			return this._InvoiceID;
		}
		set
		{
			if ((this._InvoiceID != value))
			{
				this._InvoiceID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid PatientID
	{
		get
		{
			return this._PatientID;
		}
		set
		{
			if ((this._PatientID != value))
			{
				this._PatientID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="Date NOT NULL")]
	public System.DateTime CreatedOn
	{
		get
		{
			return this._CreatedOn;
		}
		set
		{
			if ((this._CreatedOn != value))
			{
				this._CreatedOn = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmt", DbType="Float NOT NULL")]
	public double TotalAmt
	{
		get
		{
			return this._TotalAmt;
		}
		set
		{
			if ((this._TotalAmt != value))
			{
				this._TotalAmt = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string CreatedBy
	{
		get
		{
			return this._CreatedBy;
		}
		set
		{
			if ((this._CreatedBy != value))
			{
				this._CreatedBy = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this._Status = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reason", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string Reason
	{
		get
		{
			return this._Reason;
		}
		set
		{
			if ((this._Reason != value))
			{
				this._Reason = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueOn", DbType="Date NOT NULL")]
	public System.DateTime DueOn
	{
		get
		{
			return this._DueOn;
		}
		set
		{
			if ((this._DueOn != value))
			{
				this._DueOn = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionID", DbType="VarChar(MAX)")]
	public string TransactionID
	{
		get
		{
			return this._TransactionID;
		}
		set
		{
			if ((this._TransactionID != value))
			{
				this._TransactionID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaidOn", DbType="DateTime")]
	public System.Nullable<System.DateTime> PaidOn
	{
		get
		{
			return this._PaidOn;
		}
		set
		{
			if ((this._PaidOn != value))
			{
				this._PaidOn = value;
			}
		}
	}
}
#pragma warning restore 1591
