<?xml version="1.0" encoding="utf-8"?><Database Name="DB_65818_brdhc" Class="prescriptionsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=s10.winhost.com;Initial Catalog=DB_65818_brdhc;User ID=DB_65818_brdhc_user" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="myCon" Provider="System.Data.SqlClient" />
  <Table Name="dbo.brdhc_PatientPrescriptions" Member="brdhc_PatientPrescriptions">
    <Type Name="brdhc_PatientPrescription">
      <Column Name="PrescriptionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AppointmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Repeat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateWritten" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="brdhc_PatientPrescription_brdhc_PrescriptionDetail" Member="brdhc_PrescriptionDetails" ThisKey="PrescriptionId" OtherKey="PrescriptionId" Type="brdhc_PrescriptionDetail" />
    </Type>
  </Table>
  <Table Name="dbo.brdhc_PrescriptionDetails" Member="brdhc_PrescriptionDetails">
    <Type Name="brdhc_PrescriptionDetail">
      <Column Name="PrescriptionDetailsId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PrescriptionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Medicine" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Timings" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Days" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="brdhc_PatientPrescription_brdhc_PrescriptionDetail" Member="brdhc_PatientPrescription" ThisKey="PrescriptionId" OtherKey="PrescriptionId" Type="brdhc_PatientPrescription" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_SearchPatientPrescription" Method="sp_SearchPatientPrescription">
    <Parameter Name="AppointmentId" Parameter="appointmentId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_SearchPatientPrescriptionResult">
      <Column Name="AppointmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PatientName" Type="System.String" DbType="VarChar(101) NOT NULL" CanBeNull="false" />
      <Column Name="HealthCard" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DoctorName" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
      <Column Name="PrescriptionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Repeat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateWritten" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SearchPrescriptionDetails" Method="sp_SearchPrescriptionDetails">
    <Parameter Name="PrescriptionId" Parameter="prescriptionId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_SearchPrescriptionDetailsResult">
      <Column Name="PrescriptionDetailsId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrescriptionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Medicine" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Timings" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Days" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SearchPrescriptionsByPatientName" Method="sp_SearchPrescriptionsByPatientName">
    <Parameter Name="PatientName" Parameter="patientName" Type="System.String" DbType="NVarChar(256)" />
    <ElementType Name="sp_SearchPrescriptionsByPatientNameResult">
      <Column Name="AppointmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PatientName" Type="System.String" DbType="VarChar(101) NOT NULL" CanBeNull="false" />
      <Column Name="HealthCard" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DoctorName" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
      <Column Name="PrescriptionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Repeat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateWritten" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SearchPrescriptionsByDocId" Method="sp_SearchPrescriptionsByDocId">
    <Parameter Name="PatientName" Parameter="patientName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="DocId" Parameter="docId" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="sp_SearchPrescriptionsByDocIdResult">
      <Column Name="AppointmentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PatientName" Type="System.String" DbType="VarChar(101) NOT NULL" CanBeNull="false" />
      <Column Name="HealthCard" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DoctorName" Type="System.String" DbType="VarChar(101)" CanBeNull="true" />
      <Column Name="PrescriptionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Repeat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateWritten" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>