<?xml version="1.0" encoding="utf-8"?><Database Name="DB_65818_brdhc" Class="UserDetailsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=s10.winhost.com;Initial Catalog=DB_65818_brdhc;User ID=DB_65818_brdhc_user" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="myCon" Provider="System.Data.SqlClient" />
  <Table Name="dbo.aspnet_UsersInRoles" Member="aspnet_UsersInRoles">
    <Type Name="aspnet_UsersInRole">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="aspnet_Role_aspnet_UsersInRole" Member="aspnet_Role" ThisKey="RoleId" OtherKey="RoleId" Type="aspnet_Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Roles" Member="aspnet_Roles">
    <Type Name="aspnet_Role">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredRoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Association Name="aspnet_Role_aspnet_UsersInRole" Member="aspnet_UsersInRoles" ThisKey="RoleId" OtherKey="RoleId" Type="aspnet_UsersInRole" />
    </Type>
  </Table>
  <Table Name="dbo.brdhc_DoctorSpecialities" Member="brdhc_DoctorSpecialities">
    <Type Name="brdhc_DoctorSpeciality">
      <Column Name="SpecialityId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Speciality" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.brdhc_UserBasicInfo" Member="brdhc_UserBasicInfos">
    <Type Name="brdhc_UserBasicInfo">
      <Column Name="UserBasicInfoId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Gender" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Identification" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CityId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="StateId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="PostalCode" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="FamilyDoctor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JoinDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Speciality" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CommunityGroupName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_SearchUsers" Method="sp_SearchUsers">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="NVarChar(256)" />
    <ElementType Name="sp_SearchUsersResult">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(101) NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Identification" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JoinDate" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Speciality" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsLocked" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="CommunityGroupName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_LockUser" Method="sp_LockUser">
    <Parameter Name="UserId" Parameter="userId" Type="System.Guid" DbType="UniqueIdentifier" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_SearchUsersById" Method="sp_SearchUsersById">
    <Parameter Name="UserId" Parameter="userId" Type="System.Guid" DbType="UniqueIdentifier" />
    <ElementType Name="sp_SearchUsersByIdResult">
      <Column Name="UserBasicInfoId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Gender" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="Identification" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CityId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="StateId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="PostalCode" Type="System.String" DbType="VarChar(7) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Fax" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="FamilyDoctor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JoinDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Speciality" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CommunityGroupName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SearchUsersByParam" Method="sp_SearchUsersByParam">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="RoleName" Parameter="roleName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(256)" />
    <ElementType Name="sp_SearchUsersByParamResult">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(101) NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Identification" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JoinDate" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Speciality" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsLocked" Type="System.String" DbType="VarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="CommunityGroupName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SearchDoctorsBySpeciality" Method="sp_SearchDoctorsBySpeciality">
    <Parameter Name="ApplicationName" Parameter="applicationName" Type="System.String" DbType="NVarChar(256)" />
    <Parameter Name="Speciality" Parameter="speciality" Type="System.String" DbType="NVarChar(256)" />
    <ElementType Name="sp_SearchDoctorsBySpecialityResult">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(101) NOT NULL" CanBeNull="false" />
      <Column Name="DOB" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Identification" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Department" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="JoinDate" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="Speciality" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_getAllPatientNames" Method="sp_getAllPatientNames">
    <ElementType Name="sp_getAllPatientNamesResult">
      <Column Name="patientName" Type="System.String" DbType="VarChar(101) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>