#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_65818_brdhc")]
public partial class volunteerClassDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertbrdhc_volunteerOpp(brdhc_volunteerOpp instance);
  partial void Updatebrdhc_volunteerOpp(brdhc_volunteerOpp instance);
  partial void Deletebrdhc_volunteerOpp(brdhc_volunteerOpp instance);
  #endregion
	
	public volunteerClassDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["myCon"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public volunteerClassDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public volunteerClassDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public volunteerClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public volunteerClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<brdhc_volunteerOpp> brdhc_volunteerOpps
	{
		get
		{
			return this.GetTable<brdhc_volunteerOpp>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.brdhc_volunteerOpp")]
public partial class brdhc_volunteerOpp : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private System.Guid _OppId;
	
	private string _OppTitle;
	
	private string _Skills;
	
	private string _Benefits;
	
	private string _Other;
	
	private string _CommitmentHow;
	
	private string _CommitmentWhen;
	
	private string _ContactPerson;
	
	private string _Department;
	
	private string _Reviewed;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOppIdChanging(System.Guid value);
    partial void OnOppIdChanged();
    partial void OnOppTitleChanging(string value);
    partial void OnOppTitleChanged();
    partial void OnSkillsChanging(string value);
    partial void OnSkillsChanged();
    partial void OnBenefitsChanging(string value);
    partial void OnBenefitsChanged();
    partial void OnOtherChanging(string value);
    partial void OnOtherChanged();
    partial void OnCommitmentHowChanging(string value);
    partial void OnCommitmentHowChanged();
    partial void OnCommitmentWhenChanging(string value);
    partial void OnCommitmentWhenChanged();
    partial void OnContactPersonChanging(string value);
    partial void OnContactPersonChanged();
    partial void OnDepartmentChanging(string value);
    partial void OnDepartmentChanged();
    partial void OnReviewedChanging(string value);
    partial void OnReviewedChanged();
    #endregion
	
	public brdhc_volunteerOpp()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OppId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
	public System.Guid OppId
	{
		get
		{
			return this._OppId;
		}
		set
		{
			if ((this._OppId != value))
			{
				this.OnOppIdChanging(value);
				this.SendPropertyChanging();
				this._OppId = value;
				this.SendPropertyChanged("OppId");
				this.OnOppIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OppTitle", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string OppTitle
	{
		get
		{
			return this._OppTitle;
		}
		set
		{
			if ((this._OppTitle != value))
			{
				this.OnOppTitleChanging(value);
				this.SendPropertyChanging();
				this._OppTitle = value;
				this.SendPropertyChanged("OppTitle");
				this.OnOppTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Skills", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Skills
	{
		get
		{
			return this._Skills;
		}
		set
		{
			if ((this._Skills != value))
			{
				this.OnSkillsChanging(value);
				this.SendPropertyChanging();
				this._Skills = value;
				this.SendPropertyChanged("Skills");
				this.OnSkillsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Benefits", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Benefits
	{
		get
		{
			return this._Benefits;
		}
		set
		{
			if ((this._Benefits != value))
			{
				this.OnBenefitsChanging(value);
				this.SendPropertyChanging();
				this._Benefits = value;
				this.SendPropertyChanged("Benefits");
				this.OnBenefitsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other", DbType="VarChar(255)")]
	public string Other
	{
		get
		{
			return this._Other;
		}
		set
		{
			if ((this._Other != value))
			{
				this.OnOtherChanging(value);
				this.SendPropertyChanging();
				this._Other = value;
				this.SendPropertyChanged("Other");
				this.OnOtherChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommitmentHow", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
	public string CommitmentHow
	{
		get
		{
			return this._CommitmentHow;
		}
		set
		{
			if ((this._CommitmentHow != value))
			{
				this.OnCommitmentHowChanging(value);
				this.SendPropertyChanging();
				this._CommitmentHow = value;
				this.SendPropertyChanged("CommitmentHow");
				this.OnCommitmentHowChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommitmentWhen", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
	public string CommitmentWhen
	{
		get
		{
			return this._CommitmentWhen;
		}
		set
		{
			if ((this._CommitmentWhen != value))
			{
				this.OnCommitmentWhenChanging(value);
				this.SendPropertyChanging();
				this._CommitmentWhen = value;
				this.SendPropertyChanged("CommitmentWhen");
				this.OnCommitmentWhenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactPerson", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
	public string ContactPerson
	{
		get
		{
			return this._ContactPerson;
		}
		set
		{
			if ((this._ContactPerson != value))
			{
				this.OnContactPersonChanging(value);
				this.SendPropertyChanging();
				this._ContactPerson = value;
				this.SendPropertyChanged("ContactPerson");
				this.OnContactPersonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="VarChar(100)")]
	public string Department
	{
		get
		{
			return this._Department;
		}
		set
		{
			if ((this._Department != value))
			{
				this.OnDepartmentChanging(value);
				this.SendPropertyChanging();
				this._Department = value;
				this.SendPropertyChanged("Department");
				this.OnDepartmentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reviewed", DbType="VarChar(10)")]
	public string Reviewed
	{
		get
		{
			return this._Reviewed;
		}
		set
		{
			if ((this._Reviewed != value))
			{
				this.OnReviewedChanging(value);
				this.SendPropertyChanging();
				this._Reviewed = value;
				this.SendPropertyChanged("Reviewed");
				this.OnReviewedChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
